public class Main {
    public static void main(String[] args){
        Building b = new Building(20, 2, 20);
        Controller c = new Controller(b.messageCenter);
        c.start();
        b.addPassenger(1, new Passenger(5));
        b.addPassenger(1, new Passenger(5));
        b.addPassenger(1, new Passenger(5));
        b.addPassenger(1, new Passenger(5));
        b.addPassenger(1, new Passenger(5));
        b.addPassenger(1, new Passenger(5));
        b.addPassenger(1, new Passenger(5));
        b.addPassenger(1, new Passenger(5));
        b.addPassenger(1, new Passenger(5));
        b.addPassenger(1, new Passenger(5));
        b.addPassenger(1, new Passenger(5));
        b.addPassenger(1, new Passenger(5));
        b.addPassenger(1, new Passenger(5));
        b.addPassenger(1, new Passenger(5));
        b.addPassenger(1, new Passenger(5));
        b.addPassenger(1, new Passenger(5));
        b.addPassenger(1, new Passenger(5));
        b.addPassenger(1, new Passenger(5));
        b.addPassenger(1, new Passenger(5));
        b.addPassenger(1, new Passenger(5));
        b.addPassenger(1, new Passenger(5));
        b.addPassenger(1, new Passenger(5));
        b.addPassenger(1, new Passenger(5));
        b.addPassenger(1, new Passenger(5));
        b.addPassenger(1, new Passenger(5));
        b.addPassenger(1, new Passenger(5));
        b.addPassenger(1, new Passenger(5));
        b.addPassenger(1, new Passenger(5));
        b.addPassenger(1, new Passenger(5));
        b.addPassenger(1, new Passenger(5));
        b.addPassenger(1, new Passenger(5));
        b.addPassenger(1, new Passenger(5));
        b.addPassenger(1, new Passenger(5));
        b.addPassenger(1, new Passenger(5));
        b.addPassenger(1, new Passenger(5));
        b.addPassenger(1, new Passenger(5));
        b.addPassenger(1, new Passenger(5));
        b.addPassenger(1, new Passenger(5));
        b.addPassenger(1, new Passenger(5));
        b.addPassenger(1, new Passenger(5));
        b.addPassenger(1, new Passenger(5));
        b.addPassenger(1, new Passenger(5));
        b.addPassenger(1, new Passenger(5));
        b.addPassenger(1, new Passenger(5));
        b.addPassenger(1, new Passenger(5));
        b.addPassenger(1, new Passenger(5));
        b.addPassenger(1, new Passenger(5));
        b.addPassenger(1, new Passenger(5));
        b.addPassenger(1, new Passenger(5));
        b.addPassenger(1, new Passenger(5));
        b.addPassenger(1, new Passenger(5));
        b.addPassenger(1, new Passenger(5));
        b.addPassenger(1, new Passenger(5));
        b.addPassenger(2, new Passenger(5));
        b.addPassenger(3, new Passenger(5));
        b.addPassenger(7, new Passenger(5));
        b.addPassenger(9, new Passenger(5));
        b.addPassenger(10, new Passenger(5));
        b.addPassenger(12, new Passenger(5));
        b.addPassenger(13, new Passenger(5));
        b.addPassenger(16, new Passenger(20));
        b.addPassenger(1, new Passenger(5));
        b.addPassenger(1, new Passenger(5));
        b.elevatorList.get(0).addDestination(2);
        b.elevatorList.get(1).addDestination(16);
    }
}
